---
sudo: required

services:
  - docker

cache:
  - pip

language: python

python:
  - "2.7"
  - "3.5"

env:
  - OPENSHIFT_VERSION=latest
  - OPENSHIFT_VERSION=1.5
  - OPENSHIFT_VERSION=1.4
  - OPENSHIFT_VERSION=1.3

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls

before_cache:
  - rm ~/.cache/pip/log/debug.log
